### ISSUE TITLE
Argument related parsing 

### ISSUE THREAD

**Issue by deaddog** [deaddog/CommandLineParsing#1]
The current parser model does not allow for no key arguments (such as listing files).

**Comment by deaddog** [comment]
This should be implemented as a parameter with attribute NoName. 
- A parameter cannot have both Name and NoName attributes. 
- Only one parameter can be marked as NoName. 
- Commands that have a NoName parameter cannot have subcommands. 
- A NoName parameter must be a generic parameter element with an array as type.

**Comment by MikaelElkiaer** [comment]
:+1:

**Comment by deaddog** [comment]
Should be working now. Not much is documented - yet.
