### ISSUE TITLE
Prompting for required parameters

### ISSUE THREAD

**Issue by deaddog** [deaddog/CommandLineParsing#10]
Extend the `Required` attribute with a `bool allowPrompt` argument.
This argument declares that if the associated parameter is not present when executing the command, the user should be prompted for the information. When prompting, the message from the `Required` attribute can be used to prompt and the parameters `Validator` can be re-used.

**Comment by MikaelElkiaer** [comment]
:+1:

**Comment by deaddog** [comment]
This requires implementation of #18.
